//! WASM guest implementation of the `run_shell` tool.
//!
//! Shell execution is **not** performed inside the WASM sandbox — WASI does
//! not expose process spawning.  Instead this guest calls the `run-shell`
//! HOST import, which the aigent-runtime host executes under a seccomp /
//! macOS sandbox profile restricting it to the workspace directory.
//!
//! The host runs the command only after the user has approved it (when the
//! `approval_mode` is not `autonomous`).
//!
//! # Building
//! ```sh
//! cd extensions/tools-src && cargo build --release
//! ```

use std::collections::HashMap;
use std::io::{self, BufRead, Write};

// ── WIT-generated bindings ──────────────────────────────────────────────────
//
// `wit_bindgen::generate!` reads the WIT world definition and produces:
//   - Callable stubs for host-exported functions (e.g. `run_shell`).
//   - A `Guest` trait that the guest must implement (`spec`, `run`).
//
// The current runtime still uses WASIP1 stdio JSON, so the `Guest` trait
// is not wired into `main()` yet.  Only the host-export stubs are used
// here — specifically `run_shell(command, timeout_ms) -> ToolResult`.
wit_bindgen::generate!({
    world: "host",
    path: "../../wit/host.wit",
});

fn main() {
    let stdin = io::stdin();
    let mut params_json = String::new();
    for line in stdin.lock().lines() {
        params_json.push_str(&line.expect("failed to read stdin"));
        params_json.push('\n');
    }
    let args: HashMap<String, String> =
        serde_json::from_str(params_json.trim()).unwrap_or_default();

    let command = match args.get("command") {
        Some(c) => c.clone(),
        None => {
            emit_result(false, "missing required param: command");
            return;
        }
    };
    let timeout_ms: u32 = args
        .get("timeout_secs")
        .and_then(|v| v.parse::<u32>().ok())
        .unwrap_or(30)
        .saturating_mul(1000);

    // Delegate actual execution to the host (outside the WASM sandbox).
    // The host validates the command against the approval policy, runs it
    // under seccomp/macOS sandbox, and returns the output.
    //
    // `run_shell` is generated by wit-bindgen from the host.wit definition:
    //   export run-shell: func(command: string, timeout-ms: u32) -> tool-result;
    let result = run_shell(&command, timeout_ms);
    emit_result(result.success, &result.output);
}

fn emit_result(success: bool, output: &str) {
    let out = serde_json::json!({ "success": success, "output": output });
    let _ = writeln!(io::stdout().lock(), "{}", out);
}
