use serde::{Deserialize, Serialize};

use crate::agent_loop::{ReactPhase, SwarmRole};

// ToolCallInfo and ToolResult are defined in the thinker crate.
// Re-export them here so BackendEvent can use them and downstream code
// that pattern-matches on BackendEvent variants continues to work.
pub use aigent_thinker::{ToolCallInfo, ToolResult};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum BackendEvent {
    Token(String),
    ToolCallStart(ToolCallInfo),
    ToolCallEnd(ToolResult),
    Thinking,
    /// Emitted when a manual /sleep command is in progress so the TUI can
    /// show a dedicated animated indicator without polluting the chat log.
    SleepCycleRunning,
    /// Incremental stage update from a running sleep cycle.
    /// Displayed as a distinct system line in the chat window so
    /// the user can follow the pipeline's progress.
    SleepProgress(String),
    Done,
    Error(String),
    MemoryUpdated,
    /// A turn submitted from an external source (e.g. Telegram). Contains
    /// the source label and the original user message so the TUI can display
    /// a user bubble before the streaming assistant response arrives.
    ExternalTurn { source: String, content: String },
    /// A short insight extracted by the inline reflection pass that ran after
    /// the turn completed.  Clients may display these in a side-panel.
    ReflectionInsight(String),
    /// A new belief that was recorded during the inline reflection pass.
    BeliefAdded { claim: String, confidence: f32 },
    /// An unprompted message generated by the proactive background task.
    ProactiveMessage { content: String },
    /// Instructs clients to discard any partially-streamed assistant message.
    /// Emitted when the fallback tool-detection path discovers that the
    /// streamed reply was raw tool JSON — the ugly tokens are cleared before
    /// the corrected response is streamed.
    ClearStream,
    /// A brief thought from the external thinking loop. The TUI renders
    /// these as dim grey "[Thinking]: …" lines so the user sees the model's
    /// chain-of-thought without filling the chat with long monologues.
    AgentThought(String),
    /// Progress update from the parallel sub-agent pipeline (spawn / complete).
    /// The TUI renders these as "🤖 …" chat bubbles distinct from the captain's
    /// thought bubbles, so the user sees that specialists are working.
    SubAgentProgress(String),

    // ── ReAct state machine events ─────────────────────────────────
    /// Emitted when the ReAct loop transitions to a new phase.
    ReactPhaseChanged {
        phase: ReactPhase,
        round: u32,
        max_rounds: u32,
    },
    /// Emitted when a sub-agent is spawned within a swarm.
    SubAgentSpawned {
        role: SwarmRole,
        task: String,
    },
    /// Emitted when a sub-agent completes its work.
    SubAgentCompleted {
        role: SwarmRole,
        success: bool,
        summary: String,
    },
    /// Emitted after a `/model set`, `/model provider`, or similar config
    /// change so the TUI header can refresh the displayed model badge.
    ConfigUpdated {
        model: String,
        provider: String,
    },
}
