use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCallInfo {
    pub name: String,
    pub args: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolResult {
    pub name: String,
    pub success: bool,
    pub output: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum BackendEvent {
    Token(String),
    ToolCallStart(ToolCallInfo),
    ToolCallEnd(ToolResult),
    Thinking,
    /// Emitted when a manual /sleep command is in progress so the TUI can
    /// show a dedicated animated indicator without polluting the chat log.
    SleepCycleRunning,
    Done,
    Error(String),
    MemoryUpdated,
    /// A turn submitted from an external source (e.g. Telegram). Contains
    /// the source label and the original user message so the TUI can display
    /// a user bubble before the streaming assistant response arrives.
    ExternalTurn { source: String, content: String },
    /// A short insight extracted by the inline reflection pass that ran after
    /// the turn completed.  Clients may display these in a side-panel.
    ReflectionInsight(String),
    /// A new belief that was recorded during the inline reflection pass.
    BeliefAdded { claim: String, confidence: f32 },
    /// An unprompted message generated by the proactive background task.
    ProactiveMessage { content: String },
}
