use serde::{Deserialize, Serialize};

use crate::agent_loop::{ReactPhase, SwarmRole};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCallInfo {
    pub name: String,
    pub args: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolResult {
    pub name: String,
    pub success: bool,
    pub output: String,
    /// Wall-clock duration of the tool invocation in milliseconds.
    #[serde(default)]
    pub duration_ms: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum BackendEvent {
    Token(String),
    ToolCallStart(ToolCallInfo),
    ToolCallEnd(ToolResult),
    Thinking,
    /// Emitted when a manual /sleep command is in progress so the TUI can
    /// show a dedicated animated indicator without polluting the chat log.
    SleepCycleRunning,
    /// Incremental stage update from a running sleep cycle.
    /// Displayed as a distinct system line in the chat window so
    /// the user can follow the pipeline's progress.
    SleepProgress(String),
    Done,
    Error(String),
    MemoryUpdated,
    /// A turn submitted from an external source (e.g. Telegram). Contains
    /// the source label and the original user message so the TUI can display
    /// a user bubble before the streaming assistant response arrives.
    ExternalTurn { source: String, content: String },
    /// A short insight extracted by the inline reflection pass that ran after
    /// the turn completed.  Clients may display these in a side-panel.
    ReflectionInsight(String),
    /// A new belief that was recorded during the inline reflection pass.
    BeliefAdded { claim: String, confidence: f32 },
    /// An unprompted message generated by the proactive background task.
    ProactiveMessage { content: String },
    /// Instructs clients to discard any partially-streamed assistant message.
    /// Emitted when the fallback tool-detection path discovers that the
    /// streamed reply was raw tool JSON — the ugly tokens are cleared before
    /// the corrected response is streamed.
    ClearStream,
    /// A brief thought from the external thinking loop. The TUI renders
    /// these as dim grey "[Thinking]: …" lines so the user sees the model's
    /// chain-of-thought without filling the chat with long monologues.
    AgentThought(String),

    // ── ReAct state machine events ─────────────────────────────────
    /// Emitted when the ReAct loop transitions to a new phase.
    ReactPhaseChanged {
        phase: ReactPhase,
        round: u32,
        max_rounds: u32,
    },
    /// Emitted when a sub-agent is spawned within a swarm.
    SubAgentSpawned {
        role: SwarmRole,
        task: String,
    },
    /// Emitted when a sub-agent completes its work.
    SubAgentCompleted {
        role: SwarmRole,
        success: bool,
        summary: String,
    },
    /// Emitted after a `/model set`, `/model provider`, or similar config
    /// change so the TUI header can refresh the displayed model badge.
    ConfigUpdated {
        model: String,
        provider: String,
    },
}

